### ISSUE TITLE
News content missing in edit form

### ISSUE THREAD

**Issue by EwelinaSkrzypacz** [blumilksoftware/keating#116]
1. Login into app
2. Go to "Aktualności"
3. Create some news with content
4. Edit the news
5. See that content in edit news form is empty

**Comment by EwelinaSkrzypacz** [comment]
I think there is a problem with all places, where we have WYSIWYG - like "Sekcje", "FAQ" and "Kursy"

**Comment by kamilpiech97** [comment]
Its should be fixed in #120, I downgraded `quill` package to previous version and fixed version to specific release. We should create new one issue for update quill and check if all working good.

**Comment by EwelinaSkrzypacz** [comment]
I had to delete directory `node_modules` and run `npm install` - after these steps it works for me
