### ISSUE TITLE
Warnings in console

### ISSUE THREAD

**Issue by EwelinaSkrzypacz** [blumilksoftware/keating#121]
I noticed some warnings in console like this:

![image](https://github.com/user-attachments/assets/85608c07-81c4-4a14-81d7-63b5eff32bea)

**Comment by kamilpiech97** [comment]
I am closing that issue because this is connected with `sanitize-html` which added by @krzysztofrewak and next in that [PR](https://github.com/blumilksoftware/keating/pull/120) I removed that package. Why? Because we are using in project `DOMPurify` package for html sanitizing.
