### ISSUE TITLE
Courses page

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/keating#26]
Courses should be visible for guests:
- [ ] on `/kursy` page with nice table
- [ ] on `/kursy/{id}` pages with course details

Table should include course code, full name, assigned field, semester number, form. Active courses should go first. 

![image](https://github.com/blumilksoftware/keating/assets/10898728/d2e992dd-8666-4e34-9592-07602ecd00d0)

This is related to #10  and should be done after implementation of this task.

**Comment by kamilpiech97** [comment]
Closed with #120
